-- Round-12 §1A — idempotent seed-defaults migration.
--
-- Runs on every `prisma migrate deploy`. Inserts the floor-row set
-- a usable BreakFix Triage instance needs (8 EmailTemplate rows,
-- 1 example EmailRule, 33 Holiday rows for 2026-2028).
--
-- Idempotency strategy:
--   - EmailTemplate: ON CONFLICT (key) DO NOTHING
--   - EmailRule: WHERE NOT EXISTS (...) on (scope, event, templateId)
--   - Holiday: WHERE NOT EXISTS (...) on (date, scope, scopeId)
--
-- Dates were generated by src/lib/holidays/federal.ts +
-- prisma/lib/federal-holidays.ts (lockstep-pinned). Regenerate
-- annually as 2029+ comes into scope.
--
-- Audit rows: every insert writes an AuditLog with action =
-- 'system_seed' and after JSON containing { source: 'migration',
-- seededAt: now() }. The audit trail is the canonical "is this row
-- seeded or operator-added" answer per the §1A spec.

-- =====================================================================
-- EmailTemplate seeds
-- =====================================================================

INSERT INTO "EmailTemplate" ("id", "key", "subject", "bodyHtml", "bodyText", "variables", "createdAt", "updatedAt")
VALUES
  (
    'seed_tpl_ticket_created',
    'ticket_created',
    'Ticket {{ticket.number}} created — {{ticket.summary}}',
    '<p>A new ticket was created for {{school.name}}.</p><p><strong>{{ticket.summary}}</strong></p><p><a href="{{link}}">Open ticket</a></p>',
    'A new ticket was created for {{school.name}}: {{ticket.summary}}. Open: {{link}}',
    '{"type":"object","required":["ticket","school","link"],"properties":{"ticket":{"type":"object"},"school":{"type":"object"},"link":{"type":"string"}}}',
    NOW(), NOW()
  ),
  (
    'seed_tpl_ticket_assigned',
    'ticket_assigned',
    'Ticket {{ticket.number}} assigned to {{assignee.name}}',
    '<p>{{ticket.number}} was assigned to {{assignee.name}}.</p><p><a href="{{link}}">Open ticket</a></p>',
    'Ticket {{ticket.number}} assigned to {{assignee.name}}. Open: {{link}}',
    '{"type":"object","required":["ticket","assignee","link"],"properties":{"ticket":{"type":"object"},"assignee":{"type":"object"},"link":{"type":"string"}}}',
    NOW(), NOW()
  ),
  (
    'seed_tpl_ticket_status_changed',
    'ticket_status_changed',
    'Ticket {{ticket.number}} now {{ticket.state}}',
    '<p>{{ticket.number}} moved to <strong>{{ticket.state}}</strong>.</p><p><a href="{{link}}">Open ticket</a></p>',
    'Ticket {{ticket.number}} moved to {{ticket.state}}. Open: {{link}}',
    '{"type":"object","required":["ticket","link"],"properties":{"ticket":{"type":"object"},"link":{"type":"string"}}}',
    NOW(), NOW()
  ),
  (
    'seed_tpl_quote_sent',
    'quote_sent',
    'Quote {{quote.number}} for ticket {{ticket.number}}',
    '<p>A repair quote is ready for ticket {{ticket.number}}.</p><p>Total: {{quote.total}}</p><p><a href="{{link}}">Review and approve</a></p>',
    'Quote ready for {{ticket.number}}. Total: {{quote.total}}. Review: {{link}}',
    '{"type":"object","required":["ticket","quote","link"],"properties":{"ticket":{"type":"object"},"quote":{"type":"object"},"link":{"type":"string"}}}',
    NOW(), NOW()
  ),
  (
    'seed_tpl_daily_digest',
    'daily_digest',
    'BreakFix Triage daily digest — {{date}}',
    '<p>Daily summary for {{date}}.</p><p>Open tickets: {{counts.open}}</p><p>Awaiting parts: {{counts.parts}}</p><p>Approaching SLA: {{counts.sla}}</p>',
    'Daily summary for {{date}}. Open: {{counts.open}}. Awaiting parts: {{counts.parts}}. Approaching SLA: {{counts.sla}}.',
    '{"type":"object","required":["date","counts"],"properties":{"date":{"type":"string"},"counts":{"type":"object"}}}',
    NOW(), NOW()
  ),
  (
    'seed_tpl_delivery_scheduled',
    'delivery_scheduled',
    'Delivery scheduled for ticket {{ticket.number}}',
    '<p>The repaired device for {{ticket.number}} will be delivered on {{stop.scheduledFor}}.</p>',
    'Delivery for {{ticket.number}} scheduled {{stop.scheduledFor}}.',
    '{"type":"object","required":["ticket","stop"],"properties":{"ticket":{"type":"object"},"stop":{"type":"object"}}}',
    NOW(), NOW()
  ),
  (
    'seed_tpl_sla_breach_warning',
    'sla_breach_warning',
    'SLA approaching for ticket {{ticket.number}}',
    '<p>{{ticket.number}} is approaching its SLA threshold ({{sla.threshold}} days).</p>',
    'SLA approaching for {{ticket.number}} ({{sla.threshold}} days).',
    '{"type":"object","required":["ticket","sla"],"properties":{"ticket":{"type":"object"},"sla":{"type":"object"}}}',
    NOW(), NOW()
  ),
  (
    'seed_tpl_ticket_closed',
    'ticket_closed',
    'Ticket {{ticket.number}} closed',
    '<p>{{ticket.number}} is closed. {{summary}}</p>',
    'Ticket {{ticket.number}} closed. {{summary}}',
    '{"type":"object","required":["ticket"],"properties":{"ticket":{"type":"object"}}}',
    NOW(), NOW()
  )
ON CONFLICT ("key") DO NOTHING;

-- Audit rows for each EmailTemplate seed insert.
INSERT INTO "AuditLog" ("id", "actorUserId", "entityType", "entityId", "action", "after", "createdAt")
SELECT
  'seed_audit_tpl_' || t."key",
  NULL,
  'EmailTemplate',
  t."id",
  'system_seed',
  jsonb_build_object('source', 'migration', 'seededAt', NOW()::text, 'key', t."key"),
  NOW()
FROM "EmailTemplate" t
WHERE t."id" LIKE 'seed_tpl_%'
  AND NOT EXISTS (
    SELECT 1 FROM "AuditLog" a
    WHERE a."entityType" = 'EmailTemplate'
      AND a."entityId" = t."id"
      AND a."action" = 'system_seed'
  );

-- =====================================================================
-- EmailRule seeds — one example Global rule on ticket_created.
-- Disabled by default per Round-5 §1 contract; admins opt-in.
-- =====================================================================

INSERT INTO "EmailRule" ("id", "scope", "scopeId", "event", "recipients", "templateId", "enabled", "createdAt", "updatedAt")
SELECT
  'seed_rule_ticket_created_global',
  'GLOBAL',
  NULL,
  'ticket_created',
  '{"to":[{"kind":"school_spoc"},{"kind":"ticket_reporter"}],"cc":[{"kind":"wynndalco_team"}],"bcc":[]}'::jsonb,
  'seed_tpl_ticket_created',
  FALSE,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM "EmailRule"
  WHERE "scope" = 'GLOBAL' AND "event" = 'ticket_created' AND "templateId" = 'seed_tpl_ticket_created'
);

INSERT INTO "AuditLog" ("id", "actorUserId", "entityType", "entityId", "action", "after", "createdAt")
SELECT
  'seed_audit_rule_ticket_created',
  NULL,
  'EmailRule',
  'seed_rule_ticket_created_global',
  'system_seed',
  jsonb_build_object('source', 'migration', 'seededAt', NOW()::text, 'event', 'ticket_created'),
  NOW()
WHERE EXISTS (SELECT 1 FROM "EmailRule" WHERE "id" = 'seed_rule_ticket_created_global')
  AND NOT EXISTS (
    SELECT 1 FROM "AuditLog"
    WHERE "entityType" = 'EmailRule'
      AND "entityId" = 'seed_rule_ticket_created_global'
      AND "action" = 'system_seed'
  );

-- =====================================================================
-- Holiday seeds — 11 federal holidays × 3 years (2026, 2027, 2028).
-- Dates verified against src/lib/holidays/federal.ts. Regenerate
-- annually as 2029+ comes into scope (add a new migration).
-- =====================================================================

INSERT INTO "Holiday" ("id", "date", "label", "scope", "scopeId", "createdAt")
SELECT id, date::date, label, 'GLOBAL'::"HolidayScope", NULL, NOW()
FROM (VALUES
  -- 2026
  ('seed_hol_2026_new_year', '2026-01-01', 'New Year''s Day'),
  ('seed_hol_2026_mlk', '2026-01-19', 'Martin Luther King Jr. Day'),
  ('seed_hol_2026_washington', '2026-02-16', 'Washington''s Birthday'),
  ('seed_hol_2026_memorial', '2026-05-25', 'Memorial Day'),
  ('seed_hol_2026_juneteenth', '2026-06-19', 'Juneteenth'),
  ('seed_hol_2026_independence', '2026-07-04', 'Independence Day'),
  ('seed_hol_2026_labor', '2026-09-07', 'Labor Day'),
  ('seed_hol_2026_columbus', '2026-10-12', 'Columbus Day'),
  ('seed_hol_2026_veterans', '2026-11-11', 'Veterans Day'),
  ('seed_hol_2026_thanksgiving', '2026-11-26', 'Thanksgiving Day'),
  ('seed_hol_2026_christmas', '2026-12-25', 'Christmas Day'),
  -- 2027
  ('seed_hol_2027_new_year', '2027-01-01', 'New Year''s Day'),
  ('seed_hol_2027_mlk', '2027-01-18', 'Martin Luther King Jr. Day'),
  ('seed_hol_2027_washington', '2027-02-15', 'Washington''s Birthday'),
  ('seed_hol_2027_memorial', '2027-05-31', 'Memorial Day'),
  ('seed_hol_2027_juneteenth', '2027-06-19', 'Juneteenth'),
  ('seed_hol_2027_independence', '2027-07-04', 'Independence Day'),
  ('seed_hol_2027_labor', '2027-09-06', 'Labor Day'),
  ('seed_hol_2027_columbus', '2027-10-11', 'Columbus Day'),
  ('seed_hol_2027_veterans', '2027-11-11', 'Veterans Day'),
  ('seed_hol_2027_thanksgiving', '2027-11-25', 'Thanksgiving Day'),
  ('seed_hol_2027_christmas', '2027-12-25', 'Christmas Day'),
  -- 2028
  ('seed_hol_2028_new_year', '2028-01-01', 'New Year''s Day'),
  ('seed_hol_2028_mlk', '2028-01-17', 'Martin Luther King Jr. Day'),
  ('seed_hol_2028_washington', '2028-02-21', 'Washington''s Birthday'),
  ('seed_hol_2028_memorial', '2028-05-29', 'Memorial Day'),
  ('seed_hol_2028_juneteenth', '2028-06-19', 'Juneteenth'),
  ('seed_hol_2028_independence', '2028-07-04', 'Independence Day'),
  ('seed_hol_2028_labor', '2028-09-04', 'Labor Day'),
  ('seed_hol_2028_columbus', '2028-10-09', 'Columbus Day'),
  ('seed_hol_2028_veterans', '2028-11-11', 'Veterans Day'),
  ('seed_hol_2028_thanksgiving', '2028-11-23', 'Thanksgiving Day'),
  ('seed_hol_2028_christmas', '2028-12-25', 'Christmas Day')
) AS new_holidays(id, date, label)
WHERE NOT EXISTS (
  SELECT 1 FROM "Holiday" h
  WHERE h."date" = new_holidays.date::date
    AND h."scope" = 'GLOBAL'
    AND h."scopeId" IS NULL
);

-- Audit rows for each Holiday seed insert.
INSERT INTO "AuditLog" ("id", "actorUserId", "entityType", "entityId", "action", "after", "createdAt")
SELECT
  'seed_audit_hol_' || h."id",
  NULL,
  'Holiday',
  h."id",
  'system_seed',
  jsonb_build_object('source', 'migration', 'seededAt', NOW()::text, 'date', h."date"::text, 'label', h."label"),
  NOW()
FROM "Holiday" h
WHERE h."id" LIKE 'seed_hol_%'
  AND NOT EXISTS (
    SELECT 1 FROM "AuditLog" a
    WHERE a."entityType" = 'Holiday'
      AND a."entityId" = h."id"
      AND a."action" = 'system_seed'
  );
